export const YouTrackIssueFields = [
  'id',
  // 'attachments',
  // 'comments',
  // 'commentsCount',
  'created',
  // 'customFields',
  'description',
  // 'draftOwner',
  'externalIssue',
  'idReadable',
  'isDraft',
  // 'links',
  'numberInProject',
  // 'parent',
  // 'pinnedComments',
  // 'project',
  // 'reporter',
  'resolved',
  // 'subtasks',
  'summary',
  // 'tags',
  'updated',
  // 'updater',
  // 'visibility',
  // 'voters',
  // 'votes',
  // 'watchers',
  'wikifiedDescription',
].join();
